#!/usr/bin/env bash
# Harness review · Step 1 · Docs drift audit (harness-review spec § 3.1).
#
# Produces a draft `docs/harness-review/YYYY-MM-DD/step-1-docs.md` that lists:
#   - L{nn} entries whose referenced symbols no longer exist (grep-verified)
#   - E{nn} entries whose regression-test file is missing
#   - ref-src-claude paths referenced in `reference-sources.md` that don't exist locally
#
# The report is advisory — executing Claude reads it, decides what's real drift
# vs. false positive, and edits the docs manually. Step 1 never auto-edits.
#
# Exit 0 always. Works with either `rg` or POSIX `grep`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CLAUDE_DOCS="${REPO_ROOT}/docs/claude"
REVIEW_ROOT="${REPO_ROOT}/docs/harness-review"
DATE="$(date +%Y-%m-%d)"
OUT_DIR="${REVIEW_ROOT}/${DATE}"
OUT_FILE="${OUT_DIR}/step-1-docs.md"

mkdir -p "$OUT_DIR"

emit() { printf '%s\n' "$1" >>"$OUT_FILE"; }

HAVE_RG=0
command -v rg >/dev/null 2>&1 && HAVE_RG=1

count_matches() {
    local pat="$1" file="$2"
    if [[ $HAVE_RG -eq 1 ]]; then
        rg -c "$pat" "$file" 2>/dev/null || echo 0
    else
        grep -cE "$pat" "$file" 2>/dev/null || echo 0
    fi
}

extract_matches() {
    local pat="$1" file="$2"
    if [[ $HAVE_RG -eq 1 ]]; then
        rg -o -N "$pat" "$file" 2>/dev/null || true
    else
        grep -oE "$pat" "$file" 2>/dev/null || true
    fi
}

present_in_src() {
    local ident="$1"
    if [[ $HAVE_RG -eq 1 ]]; then
        rg -q --glob '!**/node_modules/**' --glob '!**/.next/**' -- \
            "$ident" "${REPO_ROOT}/backend" "${REPO_ROOT}/web" 2>/dev/null
    else
        grep -qrE --exclude-dir=node_modules --exclude-dir=.next -- \
            "$ident" "${REPO_ROOT}/backend" "${REPO_ROOT}/web" 2>/dev/null
    fi
}

: >"$OUT_FILE"
emit "# Step 1 · Docs 对齐差集 · ${DATE}"
emit ""
emit "_Generated by \`scripts/harness/audit-docs.sh\`. Advisory — review manually._"
emit ""
emit "## learnings.md"
emit ""

L_FILE="${CLAUDE_DOCS}/learnings.md"
if [[ -f "$L_FILE" ]]; then
    total=$(count_matches '^## L[0-9]+' "$L_FILE")
    emit "- Entries found: ${total}"
    emit ""
    emit "### Suspect · code symbols mentioned in learnings but not found in src"
    emit ""
    while IFS= read -r ident; do
        [[ -z "$ident" ]] && continue
        clean_ident="${ident//\`/}"
        if ! present_in_src "$clean_ident"; then
            emit "- [ ] \`${clean_ident}\` — mentioned in learnings but no repo match (may be stale or may be external)"
        fi
    done < <(extract_matches '`[A-Z][A-Za-z0-9_.]{4,40}`' "$L_FILE" | sort -u)
else
    emit "- (learnings.md not found)"
fi

emit ""
emit "## error-patterns.md"
emit ""

E_FILE="${CLAUDE_DOCS}/error-patterns.md"
if [[ -f "$E_FILE" ]]; then
    while IFS= read -r test_ref; do
        [[ -z "$test_ref" ]] && continue
        file_part="${test_ref%%::*}"
        if [[ ! -f "${REPO_ROOT}/backend/${file_part}" && ! -f "${REPO_ROOT}/${file_part}" ]]; then
            emit "- [ ] Regression test missing: \`${test_ref}\` (declared in error-patterns.md)"
        fi
    done < <(extract_matches 'tests/[A-Za-z0-9_/.]+::[A-Za-z0-9_]+' "$E_FILE" | sort -u)
else
    emit "- (error-patterns.md not found)"
fi

emit ""
emit "## reference-sources.md · ref-src-claude paths"
emit ""

R_FILE="${CLAUDE_DOCS}/reference-sources.md"
REF_ROOT="${REPO_ROOT}/ref-src-claude"
if [[ -f "$R_FILE" ]]; then
    if [[ ! -d "$REF_ROOT" ]]; then
        emit "- (\`ref-src-claude/\` not present locally — fetch first, then re-run)"
    else
        while IFS= read -r path; do
            [[ -z "$path" ]] && continue
            clean="${path#ref-src-claude/}"
            if [[ ! -e "${REF_ROOT}/${clean}" ]]; then
                emit "- [ ] \`${path}\` referenced but not found under ref-src-claude/"
            fi
        done < <(extract_matches 'ref-src-claude/[A-Za-z0-9_/.-]+' "$R_FILE" | sort -u)
    fi
else
    emit "- (reference-sources.md not found)"
fi

emit ""
emit "## harness-playbook.md · candidate backports"
emit ""
emit "Manual step (cannot be auto-detected reliably):"
emit "- Scan \`learnings.md\` top-to-bottom — tag each entry 'project-specific' or 'generally useful'"
emit "- For each 'generally useful' that is **not** already mirrored in \`docs/meta/harness-playbook.md\`,"
emit "  add a note here and backport in Step 2."
emit ""
emit "---"
emit ""
emit "Next: Step 2 — edit the listed docs, commit as \`chore(harness-review): docs drift cleanup\`."

echo "Audit written to ${OUT_FILE}"
