"""Core domain models (L4).

This package depends only on pydantic + stdlib. Never import frameworks here.
See product/04-architecture.md for full specifications.
"""

from allhands.core.artifact import (
    BINARY_KINDS,
    TEXT_KINDS,
    Artifact,
    ArtifactKind,
    ArtifactVersion,
)
from allhands.core.cockpit import (
    ActiveRunCard,
    ActiveRunStatus,
    ActivityEvent,
    ActivityEventKind,
    ActivityEventSeverity,
    ComponentStatus,
    ComponentStatusKind,
    ConvCard,
    HealthSnapshot,
    WorkspaceSummary,
)
from allhands.core.confirmation import Confirmation, ConfirmationStatus
from allhands.core.conversation import (
    Conversation,
    InteractionSpec,
    Message,
    MessageRole,
    RenderPayload,
    ToolCall,
    ToolCallStatus,
)
from allhands.core.employee import Employee
from allhands.core.errors import (
    ConfirmationExpired,
    ConfirmationRejected,
    DomainError,
    EmployeeNotFound,
    InvariantViolation,
    MaxDispatchDepthExceeded,
    MaxIterationsReached,
    MCPHandshakeFailed,
    SubRunFailed,
    ToolNotFound,
)
from allhands.core.mcp import MCPHealth, MCPServer, MCPTransport
from allhands.core.model import LLMModel
from allhands.core.observability import (
    BootstrapStatus,
    ObservabilityConfig,
    ObservatoryEmployeeBreakdown,
    ObservatorySummary,
    TraceSummary,
)
from allhands.core.plan import AgentPlan, PlanStep, StepStatus
from allhands.core.provider import LLMProvider
from allhands.core.skill import Skill, SkillSource
from allhands.core.task import (
    ACTIVE_STATUSES,
    PENDING_USER_STATUSES,
    TERMINAL_STATUSES,
    Task,
    TaskSource,
    TaskStatus,
    is_legal_transition,
)
from allhands.core.tool import CostHint, Tool, ToolKind, ToolScope
from allhands.core.trigger import (
    DEFAULT_MIN_INTERVAL_SECONDS,
    MIN_INTERVAL_SECONDS,
    EventEnvelope,
    EventPattern,
    TimerSpec,
    Trigger,
    TriggerAction,
    TriggerActionType,
    TriggerFire,
    TriggerFireSource,
    TriggerFireStatus,
    TriggerKind,
)

__all__ = [
    "ACTIVE_STATUSES",
    "BINARY_KINDS",
    "DEFAULT_MIN_INTERVAL_SECONDS",
    "MIN_INTERVAL_SECONDS",
    "PENDING_USER_STATUSES",
    "TERMINAL_STATUSES",
    "TEXT_KINDS",
    "ActiveRunCard",
    "ActiveRunStatus",
    "ActivityEvent",
    "ActivityEventKind",
    "ActivityEventSeverity",
    "AgentPlan",
    "Artifact",
    "ArtifactKind",
    "ArtifactVersion",
    "BootstrapStatus",
    "ComponentStatus",
    "ComponentStatusKind",
    "Confirmation",
    "ConfirmationExpired",
    "ConfirmationRejected",
    "ConfirmationStatus",
    "ConvCard",
    "Conversation",
    "CostHint",
    "DomainError",
    "Employee",
    "EmployeeNotFound",
    "EventEnvelope",
    "EventPattern",
    "HealthSnapshot",
    "InteractionSpec",
    "InvariantViolation",
    "LLMModel",
    "LLMProvider",
    "MCPHandshakeFailed",
    "MCPHealth",
    "MCPServer",
    "MCPTransport",
    "MaxDispatchDepthExceeded",
    "MaxIterationsReached",
    "Message",
    "MessageRole",
    "ObservabilityConfig",
    "ObservatoryEmployeeBreakdown",
    "ObservatorySummary",
    "PlanStep",
    "RenderPayload",
    "Skill",
    "SkillSource",
    "StepStatus",
    "SubRunFailed",
    "Task",
    "TaskSource",
    "TaskStatus",
    "TimerSpec",
    "Tool",
    "ToolCall",
    "ToolCallStatus",
    "ToolKind",
    "ToolNotFound",
    "ToolScope",
    "TraceSummary",
    "Trigger",
    "TriggerAction",
    "TriggerActionType",
    "TriggerFire",
    "TriggerFireSource",
    "TriggerFireStatus",
    "TriggerKind",
    "WorkspaceSummary",
    "is_legal_transition",
]
