"""Repository protocols — service-layer contract for persistence."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from allhands.core import (
        AgentPlan,
        Confirmation,
        ConfirmationStatus,
        Conversation,
        Employee,
        LLMModel,
        LLMProvider,
        MCPServer,
        Message,
        Skill,
    )


class EmployeeRepo(Protocol):
    async def get(self, employee_id: str) -> Employee | None: ...
    async def get_by_name(self, name: str) -> Employee | None: ...
    async def get_lead(self) -> Employee | None: ...
    async def list_all(self) -> list[Employee]: ...
    async def upsert(self, employee: Employee) -> Employee: ...
    async def delete(self, employee_id: str) -> None: ...


class ConversationRepo(Protocol):
    async def get(self, conversation_id: str) -> Conversation | None: ...
    async def create(self, conversation: Conversation) -> Conversation: ...
    async def list_for_employee(self, employee_id: str) -> list[Conversation]: ...
    async def list_messages(self, conversation_id: str) -> list[Message]: ...
    async def append_message(self, message: Message) -> Message: ...


class ConfirmationRepo(Protocol):
    async def get(self, confirmation_id: str) -> Confirmation | None: ...
    async def get_by_tool_call(self, tool_call_id: str) -> Confirmation | None: ...
    async def list_pending(self) -> list[Confirmation]: ...
    async def save(self, confirmation: Confirmation) -> None: ...
    async def update_status(
        self,
        confirmation_id: str,
        status: ConfirmationStatus,
    ) -> None: ...


class SkillRepo(Protocol):
    async def get(self, skill_id: str) -> Skill | None: ...
    async def list_all(self) -> list[Skill]: ...
    async def upsert(self, skill: Skill) -> None: ...
    async def delete(self, skill_id: str) -> None: ...


class MCPServerRepo(Protocol):
    async def get(self, server_id: str) -> MCPServer | None: ...
    async def list_all(self) -> list[MCPServer]: ...
    async def upsert(self, server: MCPServer) -> None: ...
    async def delete(self, server_id: str) -> None: ...


class LLMProviderRepo(Protocol):
    async def get(self, provider_id: str) -> LLMProvider | None: ...
    async def get_default(self) -> LLMProvider | None: ...
    async def list_all(self) -> list[LLMProvider]: ...
    async def upsert(self, provider: LLMProvider) -> LLMProvider: ...
    async def delete(self, provider_id: str) -> None: ...
    async def set_default(self, provider_id: str) -> None: ...


class AgentPlanRepo(Protocol):
    async def get(self, plan_id: str) -> AgentPlan | None: ...
    async def get_latest_for_conversation(self, conversation_id: str) -> AgentPlan | None: ...
    async def list_for_conversation(self, conversation_id: str) -> list[AgentPlan]: ...
    async def upsert(self, plan: AgentPlan) -> AgentPlan: ...
    async def delete(self, plan_id: str) -> None: ...


class LLMModelRepo(Protocol):
    async def get(self, model_id: str) -> LLMModel | None: ...
    async def list_all(self) -> list[LLMModel]: ...
    async def list_for_provider(self, provider_id: str) -> list[LLMModel]: ...
    async def upsert(self, model: LLMModel) -> LLMModel: ...
    async def delete(self, model_id: str) -> None: ...
