"""Repository protocols.

Concrete SQLAlchemy implementations land in subsequent PRs. Keeping the protocols
here pins the service-layer contract early so execution/services can be wired up
against interfaces, not concrete rows.
"""

from __future__ import annotations

from typing import Protocol

from allhands.core import Conversation, Employee, Message


class EmployeeRepo(Protocol):
    async def get(self, employee_id: str) -> Employee | None: ...
    async def get_lead(self) -> Employee | None: ...
    async def list_all(self) -> list[Employee]: ...
    async def upsert(self, employee: Employee) -> Employee: ...
    async def delete(self, employee_id: str) -> None: ...


class ConversationRepo(Protocol):
    async def get(self, conversation_id: str) -> Conversation | None: ...
    async def create(self, conversation: Conversation) -> Conversation: ...
    async def list_messages(self, conversation_id: str) -> list[Message]: ...
    async def append_message(self, message: Message) -> Message: ...
