"""Repository protocols — service-layer contract for persistence."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from datetime import datetime

    from allhands.core import (
        AgentPlan,
        Artifact,
        ArtifactVersion,
        Confirmation,
        ConfirmationStatus,
        Conversation,
        ConversationEvent,
        Employee,
        EventEnvelope,
        LLMModel,
        LLMProvider,
        LocalWorkspace,
        MCPServer,
        Message,
        ModelPriceEntry,
        ObservabilityConfig,
        Skill,
        SkillRuntime,
        Task,
        TaskStatus,
        Trigger,
        TriggerFire,
        UserInput,
        UserInputStatus,
    )


class EmployeeRepo(Protocol):
    async def get(self, employee_id: str) -> Employee | None: ...
    async def get_by_name(self, name: str) -> Employee | None: ...
    async def get_lead(self) -> Employee | None: ...
    async def list_all(
        self, *, status: str | None = None, include_archived: bool = False
    ) -> list[Employee]: ...
    async def upsert(self, employee: Employee) -> Employee: ...
    async def delete(self, employee_id: str) -> None: ...


class ConversationRepo(Protocol):
    async def get(self, conversation_id: str) -> Conversation | None: ...
    async def create(self, conversation: Conversation) -> Conversation: ...
    async def update(self, conversation: Conversation) -> Conversation: ...
    async def list_for_employee(self, employee_id: str) -> list[Conversation]: ...
    async def list_all(self) -> list[Conversation]: ...
    async def list_messages(self, conversation_id: str) -> list[Message]: ...
    async def list_messages_by_run_id(self, run_id: str) -> list[Message]: ...
    async def append_message(self, message: Message) -> Message: ...
    async def delete_messages(self, message_ids: list[str]) -> int: ...
    async def mark_messages_compacted(self, message_ids: list[str]) -> int:
        """Flip ``is_compacted=True`` on the given message ids · soft-delete
        for /compact (compact-dual-view.md). UI keeps these rows visible
        behind a fold; LLM context build path filters them out.
        """
        ...

    async def delete(self, conversation_id: str) -> bool:
        """Hard-delete a conversation + cascading rows (messages, events,
        skill runtime). Returns True if a row was removed, False if missing.
        """
        ...

    async def count_messages(self, conversation_ids: list[str]) -> dict[str, int]:
        """Batched message count for the history-panel "N 轮" badge."""
        ...


class ConfirmationRepo(Protocol):
    async def get(self, confirmation_id: str) -> Confirmation | None: ...
    async def get_by_tool_call(self, tool_call_id: str) -> Confirmation | None: ...
    async def list_pending(self) -> list[Confirmation]: ...
    async def save(self, confirmation: Confirmation) -> None: ...
    async def update_status(
        self,
        confirmation_id: str,
        status: ConfirmationStatus,
    ) -> None: ...


class UserInputRepo(Protocol):
    """ADR 0019 C3 · clarification (ask_user_question) persistence."""

    async def get(self, ui_id: str) -> UserInput | None: ...
    async def list_pending(self) -> list[UserInput]: ...
    async def save(self, ui: UserInput) -> None: ...
    async def update_status_with_answers(
        self,
        ui_id: str,
        status: UserInputStatus,
        answers: dict[str, str],
    ) -> None: ...
    async def update_status(self, ui_id: str, status: UserInputStatus) -> None: ...


class SkillRepo(Protocol):
    async def get(self, skill_id: str) -> Skill | None: ...
    async def list_all(self) -> list[Skill]: ...
    async def upsert(self, skill: Skill) -> None: ...
    async def delete(self, skill_id: str) -> None: ...


class MCPServerRepo(Protocol):
    async def get(self, server_id: str) -> MCPServer | None: ...
    async def list_all(self) -> list[MCPServer]: ...
    async def upsert(self, server: MCPServer) -> None: ...
    async def delete(self, server_id: str) -> None: ...


class LocalWorkspaceRepo(Protocol):
    async def get(self, workspace_id: str) -> LocalWorkspace | None: ...
    async def get_by_name(self, name: str) -> LocalWorkspace | None: ...
    async def list_all(self) -> list[LocalWorkspace]: ...
    async def upsert(self, workspace: LocalWorkspace) -> LocalWorkspace: ...
    async def delete(self, workspace_id: str) -> None: ...


class LLMProviderRepo(Protocol):
    async def get(self, provider_id: str) -> LLMProvider | None: ...
    async def list_all(self) -> list[LLMProvider]: ...
    async def upsert(self, provider: LLMProvider) -> LLMProvider: ...
    async def delete(self, provider_id: str) -> None: ...


class AgentPlanRepo(Protocol):
    async def get(self, plan_id: str) -> AgentPlan | None: ...
    async def get_latest_for_conversation(self, conversation_id: str) -> AgentPlan | None: ...
    async def list_for_conversation(self, conversation_id: str) -> list[AgentPlan]: ...
    async def upsert(self, plan: AgentPlan) -> AgentPlan: ...
    async def delete(self, plan_id: str) -> None: ...


class LLMModelRepo(Protocol):
    async def get(self, model_id: str) -> LLMModel | None: ...
    async def get_default(self) -> LLMModel | None: ...
    async def list_all(self) -> list[LLMModel]: ...
    async def list_for_provider(self, provider_id: str) -> list[LLMModel]: ...
    async def upsert(self, model: LLMModel) -> LLMModel: ...
    async def delete(self, model_id: str) -> None: ...
    async def set_default(self, model_id: str) -> LLMModel | None: ...


class TriggerRepo(Protocol):
    async def get(self, trigger_id: str) -> Trigger | None: ...
    async def list_all(self) -> list[Trigger]: ...
    async def list_by_kind(self, kind: str, enabled_only: bool = False) -> list[Trigger]: ...
    async def upsert(self, trigger: Trigger) -> Trigger: ...
    async def delete(self, trigger_id: str) -> None: ...


class TriggerFireRepo(Protocol):
    async def get(self, fire_id: str) -> TriggerFire | None: ...
    async def list_for_trigger(self, trigger_id: str, limit: int = 50) -> list[TriggerFire]: ...
    async def upsert(self, fire: TriggerFire) -> TriggerFire: ...
    async def count_in_window(self, seconds: int) -> int: ...


class ArtifactRepo(Protocol):
    async def get(self, artifact_id: str) -> Artifact | None: ...
    async def list_for_workspace(
        self,
        workspace_id: str,
        *,
        kind: str | None = None,
        name_prefix: str | None = None,
        pinned_only: bool = False,
        include_deleted: bool = False,
        limit: int = 100,
        conversation_id: str | None = None,
        employee_id: str | None = None,
        status: str | None = None,
        tag: str | None = None,
        created_after: datetime | None = None,
        created_before: datetime | None = None,
        q: str | None = None,
        sort: str = "updated_at_desc",
    ) -> list[Artifact]: ...
    async def search(self, workspace_id: str, query: str, limit: int = 50) -> list[Artifact]: ...
    async def list_by_run(self, run_id: str) -> list[Artifact]: ...
    async def upsert(self, artifact: Artifact) -> Artifact: ...
    async def soft_delete(self, artifact_id: str, deleted_at: datetime) -> None: ...
    async def list_versions(self, artifact_id: str) -> list[ArtifactVersion]: ...
    async def get_version(self, artifact_id: str, version: int) -> ArtifactVersion | None: ...
    async def save_version(self, version: ArtifactVersion) -> None: ...


class EventRepo(Protocol):
    async def save(self, event: EventEnvelope) -> None: ...
    async def list_recent(
        self,
        limit: int = 100,
        *,
        workspace_id: str | None = None,
        kind_prefixes: list[str] | None = None,
        since: datetime | None = None,
    ) -> list[EventEnvelope]: ...
    async def count_since(
        self,
        since: datetime,
        *,
        workspace_id: str | None = None,
        kind_prefixes: list[str] | None = None,
    ) -> int: ...


class TaskRepo(Protocol):
    async def get(self, task_id: str) -> Task | None: ...
    async def get_by_run_id(self, run_id: str) -> Task | None: ...
    async def list_all(
        self,
        *,
        workspace_id: str = "default",
        statuses: list[TaskStatus] | None = None,
        assignee_id: str | None = None,
        limit: int = 100,
    ) -> list[Task]: ...
    async def count_active(self, workspace_id: str = "default") -> int: ...
    async def upsert(self, task: Task) -> Task: ...


class ObservabilityConfigRepo(Protocol):
    """Single-row observability_config read/write.

    Implementations ensure exactly one row (id=1) exists after migration 0012.
    """

    async def load(self) -> ObservabilityConfig: ...
    async def save(self, config: ObservabilityConfig) -> ObservabilityConfig: ...


class SkillRuntimeRepo(Protocol):
    """Per-conversation SkillRuntime checkpointing (ADR 0011 · 原则 7).

    Used by ChatService to keep `resolved_skills` / `resolved_fragments` across
    process restarts. The in-memory cache is the hot path; repo is read on
    cache miss, written at turn boundaries, and deleted on compact.
    """

    async def load(self, conversation_id: str) -> SkillRuntime | None: ...
    async def save(self, conversation_id: str, runtime: SkillRuntime) -> None: ...
    async def delete(self, conversation_id: str) -> None: ...


class ConversationEventRepo(Protocol):
    """ADR 0017 · append-only event log for conversation history.

    This is the *authoritative* source of truth for what happened in a
    conversation. ``Message`` rows are a projection cache derived from these
    events so the existing ``/api/conversations/{id}/messages`` endpoint
    stays unchanged for the frontend.
    """

    async def append(self, event: ConversationEvent) -> ConversationEvent: ...

    async def list_by_conversation(
        self,
        conversation_id: str,
        *,
        include_compacted: bool = True,
        subagent_id: str | None = None,
    ) -> list[ConversationEvent]: ...

    async def get(self, event_id: str) -> ConversationEvent | None: ...

    async def get_by_idempotency_key(
        self, conversation_id: str, idempotency_key: str
    ) -> ConversationEvent | None: ...

    async def find_orphan_turns(self, conversation_id: str) -> list[str]: ...

    async def next_sequence(self, conversation_id: str) -> int: ...

    async def mark_compacted(self, event_ids: list[str]) -> None: ...


class ModelPriceRepo(Protocol):
    """Runtime overlay for per-model token pricing.

    The code-side seed (``services/model_pricing.py``) ships defaults; this
    repo lets an Agent (or admin) override / extend that table without a
    redeploy. Lookup order in callers: DB row → code seed → ``0.0``.
    """

    async def list_all(self) -> list[ModelPriceEntry]: ...

    async def get(self, model_ref: str) -> ModelPriceEntry | None: ...

    async def upsert(self, entry: ModelPriceEntry) -> ModelPriceEntry: ...

    async def delete(self, model_ref: str) -> bool: ...
